name: 每天自动更新中国的域名和IP
on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间0点0分，北京时间需要+8小时，代表北京时间上午8点运行
    - cron: '0 0 * * *'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.1
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install requests
      - name: cn-domain-ip
        run: |
          python3 install.py

      - name: Push artifacts to release branch
        run: |
          git config --local user.email "150651687+chenyk1219@users.noreply.github.com"
          git config --local user.name "chenyk1219"
  
          git fetch
          git checkout release
  
          git checkout --orphan release-orphan
  
          /bin/cp -rf dist/ChinaIP.list ./
          /bin/cp -rf dist/ChinaDomain.list ./
          /bin/cp -rf dist/RealIP.list ./
          /bin/cp -rf dist/UnBreak.list ./
          /bin/cp -rf dist/adg.list ./
          /bin/cp -rf dist/Unblocking.list ./
  
          git add ChinaIP.list
          git add RealIP.list
          git add ChinaDomain.list
          git add UnBreak.list
          git add adg.list
          git add Unblocking.list
          git commit -am "Updated at $(date)"
  
          git branch -D release
          git branch -m release

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          force: true
